import { cp } from "node:fs/promises";

const root = import.meta.dir;

const result = await Bun.build({
  entrypoints: [`${root}/src/popup.ts`],
  outdir: `${root}/dist`,
  target: "browser",
  format: "iife",
  minify: true,
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

await cp(`${root}/public`, `${root}/dist`, { recursive: true });
await cp(
  `${root}/node_modules/highlight.js/styles/github-dark.min.css`,
  `${root}/dist/hljs.css`,
);

// pin the extension ID for native messaging (key generated by install-host)
const keyFile = Bun.file(`${root}/.key.json`);
if (await keyFile.exists()) {
  const { key } = await keyFile.json();
  const manifest = await Bun.file(`${root}/dist/manifest.json`).json();
  await Bun.write(`${root}/dist/manifest.json`, JSON.stringify({ ...manifest, key }, null, 2));
}

console.log("built extension/dist");
